name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            slug: chrisvogt/teachersalary.info
